import { Metadata } from 'next';
import './globals.css';
import { TheHeader } from './components/Header';
import { TheFooter } from './components/Footer';

export const metadata: Metadata = {
  title: 'Next',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TheHeader />
        <main className="container">{children}</main>
        <TheFooter />
      </body>
    </html>
  );
}
